version: '3.8'

services:

  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: backend-despachos
    restart: always
    environment:
      DB_ENDPOINT: 10.0.2.7
      DB_PORT: 3306
      DB_NAME: innovatech_db
      DB_USERNAME: innovatech
      DB_PASSWORD: innovatech123
    ports:
      - "8080:8080"
    networks:
      - innovatech-network

  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: backend-ventas
    restart: always
    environment:
      DB_ENDPOINT: 10.0.2.7
      DB_PORT: 3306
      DB_NAME: innovatech_db
      DB_USERNAME: innovatech
      DB_PASSWORD: innovatech123
    ports:
      - "8081:8081"
    networks:
      - innovatech-network

  frontend:
    build:
      context: ./front_despacho
    container_name: frontend-innovatech
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend-despachos
      - backend-ventas
    networks:
      - innovatech-network

networks:
  innovatech-network:
    driver: bridge
    
